In [3]:
import random
import numpy as np
import torch
import tensorflow as tf

In [45]:
# CAU 1
# Numpy array
np.random.seed(2024)
arr_np = np.random.randint(-10,10,(3,4))
print('* Numpy array:')
print(arr_np)
print(arr_np.T)
print(arr_np@arr_np.T)

# Pytorch tensor
torch.random.manual_seed(2024)
arr_pt = torch.randint(-10,10,(3,4))
print('* Pytorch tensor:')
print(arr_pt)
print(arr_pt.T)
print(arr_pt@arr_pt.T)

# Tensorflow tensor
arr_tf = tf.random.uniform(
    (3,4),
    minval=-10,
    maxval=10,
    dtype=tf.dtypes.int32,
    seed=2024)
print('* Tensorflow tensor:')
print(arr_tf)
print(tf.transpose(arr_tf))
print(arr_tf@tf.transpose(arr_tf))

* Numpy array:
[[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
[[ -2  -1  -8]
 [-10  -9 -10]
 [-10  -7  -5]
 [ -6   0   7]]
[[240 162 124]
 [162 131 133]
 [124 133 238]]
* Pytorch tensor:
tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
tensor([[  2,  -7,   3],
        [  0, -10,   9],
        [ -6,   0,   7],
        [-10,   1,  -6]])
tensor([[ 140,  -24,   24],
        [ -24,  150, -117],
        [  24, -117,  175]])
* Tensorflow tensor:
tf.Tensor(
[[  8 -10   6 -10]
 [  4   2   0  -3]
 [ -3   3   3   4]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[  8   4  -3]
 [-10   2   3]
 [  6   0   3]
 [-10  -3   4]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[300  42 -76]
 [ 42  29 -18]
 [-76 -18  43]], shape=(3, 3), dtype=int32)


In [46]:
# CAU 2
# Numpy array
np.random.seed(2024)
arr_np = np.random.randint(-10,10,(3,3))
sum_np = arr_np.sum()
sum_axis0_np = arr_np.sum(axis=0)
sum_axis1_np = arr_np.sum(axis=1)
print('* Numpy array:')
print(arr_np)
print(f'Sum (axis=None): {sum_np}')
print(f'Sum (axis=0): {sum_axis0_np}')
print(f'Sum (axis=1): {sum_axis1_np}')

# Pytorch tensor
torch.random.manual_seed(2024)
arr_pt = torch.randint(-10,10,(3,3))
sum_pt = arr_pt.sum()
sum_axis0_pt = arr_pt.sum(axis=0)
sum_axis1_pt = arr_pt.sum(axis=1)
print('* Pytorch tensor:')
print(arr_pt)
print(f'Sum (axis=None): {sum_pt}')
print(f'Sum (axis=0): {sum_axis0_pt}')
print(f'Sum (axis=1): {sum_axis1_pt}')

# Tensorflow tensor
arr_tf = tf.random.uniform((3,3),
                           minval=-10, maxval=10,
                           dtype=tf.dtypes.int32,
                           seed=2024)
sum_tf = tf.math.reduce_sum(arr_tf, axis=None)
sum_axis0_tf = tf.math.reduce_sum(arr_tf, axis=0)
sum_axis1_tf = tf.math.reduce_sum(arr_tf, axis=1)
print('* Tensorflow tensor:')
print(arr_tf)
print(f'Sum (axis=None): {sum_tf}')
print(f'Sum (axis=0): {sum_axis0_tf}')
print(f'Sum (axis=1): {sum_axis1_tf}')

* Numpy array:
[[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Sum (axis=None): -53
Sum (axis=0): [-15 -11 -27]
Sum (axis=1): [-22 -16 -15]
* Pytorch tensor:
tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Sum (axis=None): -27
Sum (axis=0): tensor([ -8,  -6, -13])
Sum (axis=1): tensor([ -4, -27,   4])
* Tensorflow tensor:
tf.Tensor(
[[-5 -9 -4]
 [-4 -1 -4]
 [ 1 -3 -2]], shape=(3, 3), dtype=int32)
Sum (axis=None): -31
Sum (axis=0): [ -8 -13 -10]
Sum (axis=1): [-18  -9  -4]
