In [1]:
import numpy as np
import tensorflow as tf
import torch

In [25]:
# Cau 1:
arr_np = np.arange(0,10,1)
arr_tf = tf.range(0,10,1)
arr_pt = torch.arange(0,10,1)

print('Cau 1:')
print(f'- Numpy array: {arr_np}')
print(f'- Tensorflow tensor: {arr_tf}')
print(f'- Pytorch tensor: {arr_pt}')

Cau 1:
- Numpy array: [0 1 2 3 4 5 6 7 8 9]
- Tensorflow tensor: [0 1 2 3 4 5 6 7 8 9]
- Pytorch tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
# Cau 2:
matrx_np = np.eye(3,3)
matrx_tf = tf.eye(3,3)
matrx_pt = torch.eye(3,3)

print('Cau 2:')
print(f'- Numpy matrix:\n {matrx_np}')
print(f'- Tensorflow matrix:\n {matrx_tf}')
print(f'- Pytorch matrix:\n {matrx_pt}')

Cau 2:
- Numpy matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
- Tensorflow matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
- Pytorch matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [56]:
# Cau 3:
np.random.seed(2024)
ran_np = np.random.rand(3,4)
randint_np = np.random.randint(-10,10,(3,4))

torch.manual_seed(2024)
ran_pt = torch.rand(3,4)
randint_pt = torch.randint(-10,10,(3,4))

tf.random.set_seed(2024)
ran_tf = tf.random.uniform((3,4),minval=0, maxval=1)
randint_tf = tf.random.uniform((3,4),minval=-10, maxval=10,dtype='int32')

print('Cau 3:')
print('* Tensor trong khoang [0,1]:')
print(f'- Numpy tensor:\n {ran_np}')
print(f'- Pytorch tensor:\n {ran_pt}')
print(f'- Tensorflow tensor:\n {ran_tf}')
print('')
print('* Tensor trong khoang [-10,10]:')
print(f'- Numpy tensor:\n {randint_np}')
print(f'- Pytorch tensor:\n {randint_pt}')
print(f'- Tensorflow tensor:\n {randint_tf}')

Cau 3:
* Tensor trong khoang [0,1]:
- Numpy tensor:
 [[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
- Pytorch tensor:
 tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
- Tensorflow tensor:
 [[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]]

* Tensor trong khoang [-10,10]:
- Numpy tensor:
 [[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]
- Pytorch tensor:
 tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
- Tensorflow tensor:
 [[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]]
