In [60]:
import numpy as np
import torch
import tensorflow as tf
import random

## 1D

In [61]:
lst = []
length = random.randint(5,15)
length

11

In [62]:
while len(lst) < length:
  num = random.randint(1,10)
  lst.append(num)
lst

[2, 6, 4, 6, 2, 4, 4, 2, 10, 4, 9]

In [63]:
arr_1D = np.array(lst)
arr_1D

array([ 2,  6,  4,  6,  2,  4,  4,  2, 10,  4,  9])

In [64]:
tensor_1D_pt = torch.tensor(lst)
tensor_1D_pt

tensor([ 2,  6,  4,  6,  2,  4,  4,  2, 10,  4,  9])

In [65]:
tensor_1D_tf = tf.constant(lst)
tensor_1D_tf

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 2,  6,  4,  6,  2,  4,  4,  2, 10,  4,  9], dtype=int32)>

## 2D

In [136]:
lst_2D = []
length = random.randint(2,4)
sub_lst = []
for j in range(length):
  for i in range (length):
    sub_lst.append(random.randint(1,10))
  lst_2D.append(sub_lst)
  sub_lst = []
lst_2D

[[9, 8, 5, 3], [7, 6, 4, 3], [4, 9, 4, 2], [6, 3, 3, 1]]

In [108]:
arr_2D = np.array(lst_2D)
arr_2D

array([[ 9,  3,  5,  2],
       [ 3,  7, 10,  3],
       [ 8,  6,  9,  5],
       [ 1,  6,  3,  3]])

In [110]:
tensor_2D_pt = torch.tensor(lst_2D)
tensor_2D_pt

tensor([[ 9,  3,  5,  2],
        [ 3,  7, 10,  3],
        [ 8,  6,  9,  5],
        [ 1,  6,  3,  3]])

In [112]:
tensor_2D_tf = tf.convert_to_tensor(lst_2D)
tensor_2D_tf

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 9,  3,  5,  2],
       [ 3,  7, 10,  3],
       [ 8,  6,  9,  5],
       [ 1,  6,  3,  3]], dtype=int32)>

In [128]:
print(arr_2D.shape)
print(arr_2D.dtype)
print(type(arr_2D))

(4, 4)
int64
<class 'numpy.ndarray'>


In [129]:
print(tensor_2D_pt.shape)
print(tensor_2D_pt.dtype)
print(tensor_2D_pt.device)
print(type(tensor_2D_pt))

torch.Size([4, 4])
torch.int64
cpu
<class 'torch.Tensor'>
